development: &default
  adapter: postgresql
  database: nba_development
  encoding: utf8
  host: localhost
  min_messages: warning
  pool: 2
  timeout: 5000

test:
  <<: *default
  database: nba_test

production:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: nba_production
  pool: 5
  username: nba
  password: <%= ENV['DB_PASS'] %>
